### ISSUE TITLE
大佬，运行时报这个错是什么原因？ImportError: cannot import name 'HTTPClientFactory' from 'twisted.web.client' (unknown location)

### ISSUE THREAD

**Issue by liliners** [XWang20/WeiboCrawler#13]
ImportError: cannot import name 'HTTPClientFactory' from 'twisted.web.client' (unknown location)
![搜狗截图20220605125932](https://user-images.githubusercontent.com/106868048/172035737-7910c851-fb2d-40c3-a412-ec7f7e5c24f1.png)
![搜狗截图20220605130011](https://user-images.githubusercontent.com/106868048/172035743-e10145aa-82ce-4119-901d-fe5623f338fe.png)

**Comment by XWang20** [comment]
twisted的版本是多少？用twisted 21.2.0试一下
