### ISSUE TITLE
comment 爬虫中存在的问题

### ISSUE THREAD

**Issue by seven-coder** [XWang20/WeiboCrawler#15]
工程师您好，我发现在爬微博评论时，（1）并不能够把所有微博评论都爬下来；（2）会返回很多空白行；（3）每次执行程序，返回的结果（也就是爬下来的数量）还不一致。我想可能是评论接口有一定几率返回空白，需要重复访问多次，才有结果。我不知道您有没有考虑这个问题呢？

**Comment by XWang20** [comment]
1. 加cookie
2. 可以自己改一下文本处理函数，删除空白行
3. 微博机制引起的
