### ISSUE TITLE
comment二级评论字段

### ISSUE THREAD

**Issue by seven-coder** [XWang20/WeiboCrawler#17]
您好，请问这两个有什么区别啊？
![image](https://user-images.githubusercontent.com/71923020/236399190-bbca3fcb-6166-4456-830b-83a833bb0299.png)

**Comment by XWang20** [comment]
以随机一条评论为例：
<img width="562" alt="image" src="https://github.com/XWang20/WeiboCrawler/assets/43691322/8e51dcc3-beec-4e7d-a5f6-2f9401469c29">

**Comment by XWang20** [comment]
root_comment_id是根评论id，也就是对应的一级评论id，而reply_comment_id是该二级评论本身的id
