### ISSUE TITLE
如何增加转发者或评论者昵称？

### ISSUE THREAD

**Issue by biubiu3** [XWang20/WeiboCrawler#2]
现在有转发者或评论者id，请问如何修改，保存时可以增加转发者或评论者的昵称？

**Comment by XWang20** [comment]
第一种方法是直接爬取用户信息，即运行scrapy crawl user，
第二种是修改代码，爬取某条微博的评论/转发时直接保存昵称。
以转发为例子
1. 在[repost.py](https://github.com/XWang20/WeiboCrawler/blob/main/WeiboCrawler/spiders/repost.py)中34行添加
```python
repostItem['nick_name'] = repost['user']['screen_name']
```
2. 在[items.py](https://github.com/XWang20/WeiboCrawler/blob/main/WeiboCrawler/items.py)中`RepostItem`类中添加
```
nick_name = Field()
```
