### ISSUE TITLE
请问为什么更换了微博id之后只能抓微博下面的一条评论啊？

### ISSUE THREAD

**Issue by Ppinnacle** [XWang20/WeiboCrawler#6]
你好，请问为什么更换了微博id之后只能抓微博下面的一条评论啊？还有哪些地方需要修改？我是个小白555看不懂

**Comment by XWang20** [comment]
你好，程序之前有bug，我已经修改了，你现在看看呢

**Comment by Ppinnacle** [comment]
> 你好，程序之前有bug，我已经修改了，你现在看看呢

万分感谢！bug被修复了！
