### ISSUE TITLE
数据的具体时间获取问题

### ISSUE THREAD

**Issue by zhizk1995** [XWang20/WeiboCrawler#7]
大佬你好，想在抓取评论时获取评论的具体时间，按照网上的代码在 `comment.py` 做了增添:

`commentItem['created_at']= standardize_date(comment['created_at']).strftime('%Y-%m-%d  %H:%M:%S') `

部分结果显示 小时-分钟-秒，但都是00；还有部分结果还是只有年-月-日，不知道哪里出了问题，求解答🙏

**Comment by XWang20** [comment]
需要在[utils.py](https://github.com/XWang20/WeiboCrawler/blob/main/WeiboCrawler/spiders/utils.py#L6)里standardize_date函数中有strftime的地方换成你上面写的方式

**Comment by zhizk1995** [comment]
已经解决！
另，有没有可以直接给csv指定编码的解决方式啊？MAC端用Excel、WP S打开结果文件总是乱码，需要从文本编辑里面复制过来

**Comment by XWang20** [comment]
我用numbers打开没有乱码问题诶。

或者参考一下知乎里的这个问题？
https://www.zhihu.com/question/21414417

**Comment by zhizk1995** [comment]
感谢大佬！我尝试一下再来反馈
