### ISSUE TITLE
关键词查找问题

### ISSUE THREAD

**Issue by IsolatoWen** [XWang20/WeiboCrawler#9]
有关关键词的配置还能生效吗，我按照说明将注释掉的代码恢复了，然后设置了keyword，但是还是无法生效

**Comment by XWang20** [comment]
修改了代码，现在再试试呢。关键词搜索需要将[mblog.py](https://github.com/XWang20/WeiboCrawler/blob/main/WeiboCrawler/spiders/mblog.py#L28)中第28行代码替换为`urls = init_url_by_search()`，并在`init_url_by_search()`中增加关键词列表。

**Comment by IsolatoWen** [comment]
修改了之后是只能在全站搜索关键词吗？如果是获取某个用户的某个关键词该怎么修改呢，我这边是需要获取人民日报微博有关抑郁症的博文及相关评论的数据去做分析的
需求。然后就是昨天添加了用户cookie，还是只能获取到2021-12-21到现在的博文


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XWang20/WeiboCrawler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月7日(星期一) 晚上8:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XWang20/WeiboCrawler] 关键词查找问题 (Issue #9)





 
修改了代码，现在再试试呢。关键词搜索需要将mblog.py中第28行代码替换为urls = init_url_by_search()，并在init_url_by_search()中增加关键词列表。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XWang20** [comment]
暂时没办法获取某个用户的关键词微博。不过我看了一下抑郁症的微博不多，可以先在网页端搜索关键词后获取html，通过正则表达式把博文的url（例如https://weibo.com/2803301701/AaMlnrnhd的形式）提取出来，通过转换成微博mid（方法：http://jermic.cc/2019/02/13/weibo-url-mid-convert/），获得一个微博mid列表，通过mid列表再去爬转发和评论。
我测试了一下添加cookie爬取是没有问题的，注意要用m.weibo.cn站点的cookie。不过如果按这样获取应该也不需要cookie了。

**Comment by IsolatoWen** [comment]
好的，那我再试一下，麻烦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XWang20/WeiboCrawler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月8日(星期二) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XWang20/WeiboCrawler] 关键词查找问题 (Issue #9)





 
暂时没办法获取某个用户的关键词微博。不过我看了一下抑郁症的微博不多，可以先在网页端搜索关键词后获取html，通过正则表达式把博文的url（例如https://weibo.com/2803301701/AaMlnrnhd的形式）提取出来，通过转换成微博mid（方法：http://jermic.cc/2019/02/13/weibo-url-mid-convert/），获得一个微博mid列表，通过mid列表再去爬转发和评论。
 我测试了一下添加cookie爬取是没有问题的，注意要用m.weibo.cn站点的cookie。不过如果按这样获取应该也不需要cookie了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XWang20** [comment]
有问题随时联系！

**Comment by IsolatoWen** [comment]
你好，我这边试了下，人民日报有关抑郁症的博文还是挺多的，单独去抓每一个的好像不太现实，而且，我添加了关键字‘抑郁’、‘人民日报’，但是只有抑郁生效了，你看你那边能帮忙直接提供出定制程序或者直接数据吗，我这边可以有偿的。需求：人民日报有关抑郁症的微博及对应博文评论。时间2018-至今


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XWang20/WeiboCrawler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月8日(星期二) 上午10:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XWang20/WeiboCrawler] 关键词查找问题 (Issue #9)





 
有问题随时联系！
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
